services:
  server:
    build:
      context: .
      target: final
    image: go-server
    networks:
      - sigma
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    networks:
      - sigma
    environment:
      MYSQL_ROOT_PASSWORD: sigma
      MYSQL_DATABASE: sigma
      MYSQL_USER: sigma
      MYSQL_PASSWORD: sigma
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

networks:
  sigma:
    driver: bridge
