CREATE DATABASE IF NOT EXISTS sigma;
USE sigma;

CREATE TABLE IF NOT EXISTS sigma (
	id INT AUTO_INCREMENT PRIMARY KEY,
	token varchar(255) NOT NULL
);

CREATE USER IF NOT EXISTS 'sigma'@'%' IDENTIFIED BY 'sigma';
GRANT ALL PRIVILEGES ON sigma.* to 'sigma'@'%';
FLUSH PRIVILEGES;
